remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Back to Work Agent"
description: "Setup and Deployment Documentation"
baseurl: "/back2work-with-AI-campaign"
url: "https://fizamusthafa.github.io"

header_pages:
  - index.md
  - import-solution.md
  - publish-agent.md
  - admin-deploy-pin.md
  - deploy-pin-teams.md
  - daily-nudge.md
